name: Docker Build & Push (Dev)

on:
  push:
    branches: [ develop ]

jobs:
  docker:
    name: Build and push images to ECR
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION:    ${{ secrets.AWS_DEFAULT_REGION }}

    strategy:
      matrix:
        service: [ vote, result, seed-data, worker ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and push ${{ matrix.service }} service
        run: |
          REPO_NAME=voting-app-${{ matrix.service }}
          IMAGE_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:dev
          docker build -t $IMAGE_TAG -f app/${{ matrix.service }}/Dockerfile app/${{ matrix.service }}
          docker push $IMAGE_TAG
